apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: bt-snake
  annotations:
    description: "Description"
    iconClass: "icon-http"
    tags: "Battlesnake"
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: bt-snake
    name: bt-snake
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: bt-snake
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: bt-snake
      spec:
        containers:
        - image: quay.io/rommeljryu/bt-samplesnake:latest
          name: bt-samplesnake
          ports:
          - containerPort: 8000
          resources: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: bt-snake
    name: bt-snake
  spec:
    ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      app: bt-snake 
